alias ra='ranger'
alias p='ping www.baidu.com -c 1'
alias lg='lazygit'
alias nvrun='__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia'
alias calc='calcurse'
alias cn='env LANG=zh_CN.UTF-8'
alias ls='lsd'

alias n='neofetch'
alias no='neofetch --ascii_distro'
alias s='neofetch --ascii_distro gentoo'

#----------pacman----------
alias Syy='sudo pacman -Syy'
alias Syyu='sudo pacman -Syyu'
alias Syu='sudo pacman -Syu'
alias Ss='pacman -Ss'
alias S='sudo pacman -S'
alias Rnsc='sudo pacman -Rnsc'
alias Ql='pacman -Ql'
alias Qi='pacman -Qi'

alias conda_activate='source ~/.config/zsh/conda_activate.zsh'
alias wine32='WINEARCH=win32 WINEPREFIX=~/.wine32 wine'
alias zo='zoxide'
